version: 2.1

jobs:
  setup-and-test:
    docker:
     - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run Tests
          command: pytest test_sparse_recommender.py

      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/test-driven-development:latest .

      - run:
          name: Push Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push "$DOCKERHUB_USERNAME"/test-driven-development:latest


workflows:
  Setup_and_Test:
    jobs:
      - setup-and-test
